app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  
  auth:
    ping:
      client-id: ${PING_CLIENT_ID}
      authorization-uri: ${PING_AUTH_URI}
      token-uri: ${PING_TOKEN_URI}
      validation-uri: ${PING_VALIDATION_URI}
      jwks-uri: ${PING_JWKS_URI}
      issuer-uri: ${PING_ISSUER_URI}
    entra:
      authority: ${ENTRA_AUTHORITY:https://login.microsoftonline.com/${ENTRA_TENANT_ID}}
      client-id: ${ENTRA_CLIENT_ID}
      issuer-uri: ${ENTRA_ISSUER_URI:https://login.microsoftonline.com/${ENTRA_TENANT_ID}/v2.0}
      validation-uri: ${ENTRA_VALIDATION_URI:https://graph.microsoft.com/v1.0/me}
      gateway-m2m-audience: ${ENTRA_GATEWAY_M2M_AUDIENCE:https://graph.microsoft.com/.default}
    allowed-return-paths:
      - /dashboard
      - /profile
      - /settings
      - /admin

  m2m:
    refresh:
      enabled: ${M2M_REFRESH_ENABLED:true}
      rate: ${M2M_REFRESH_RATE:60s}
      initial-delay: ${M2M_REFRESH_INITIAL_DELAY:60s}
    retry:
      max-attempts: 15
      delay: 300ms

  security:
    auth:
      max-failures: 5
      block-duration-minutes: 15
    session:
      sliding-window-minutes: 30
      absolute-timeout-hours: 8
    required-acr: null
    required-amr: []
    max-auth-age: null

  http:
    client:
      max-idle-connections: 20
      keep-alive-duration-minutes: 5
      max-requests: 100
      max-requests-per-host: 20

  azure:
    key-vault:
      uri: ${AZURE_KEYVAULT_URI}

  redis:
    mode: ${REDIS_MODE:standalone}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6380}
    ssl:
      enabled: ${REDIS_SSL_ENABLED:true}
    cluster:
      nodes: ${REDIS_CLUSTER_NODES:}
      max-redirects: 3
    timeout: 2s
    pool:
      max-active: 16
      max-idle: 8
      min-idle: 4
      max-wait: 2s
      time-between-eviction-runs: 30s

  cache:
    session:
      local-ttl: 10s
      max-size: 10000
      refresh-threshold: 0.5
